/*
 * PreferencesDialog.java
 *
 * Created on August 26, 2002, 11:39 AM
 *
 * $Id: PreferencesDialog.java,v 1.9 2004/02/23 12:37:18 erichson Exp $
 *
 * $Log: PreferencesDialog.java,v $
 * Revision 1.9  2004/02/23 12:37:18  erichson
 * Minor cosmetic fix: setRelativeLocation now happens AFTER pack()
 *
 * Revision 1.8  2003/07/02 16:27:04  erichson
 * Forgot to check in form in last check-in.
 *
 * Revision 1.7  2003/07/02 16:26:05  erichson
 * Added missing pack() which fixes bugzilla bug 002 (LAF checkbox would disappear under buttons when using Metal LAF)
 *
 * Revision 1.6  2002/12/03 15:18:33  erichson
 * Fixed layout problem which would cause combobox to disappear
 *
 * Revision 1.5  2002/11/27 13:33:36  zachrisg
 * Changed the title of the dialog to "Look and feel".
 *
 * Revision 1.4  2002/11/26 15:20:53  zachrisg
 * Removed the "keep selection after d'n'd" button.
 *
 * Revision 1.3  2002/10/30 15:56:32  zachrisg
 * Added Id and Log tags and updated javadoc.
 *
 */

package medview.visualizer.gui;

import javax.swing.*;

import medview.visualizer.data.*; // ApplicationManager

/**
 * A dialog that lets the user choose look and feel.
 *
 * @author  erichson
 */
public class PreferencesDialog extends javax.swing.JDialog {
    
    
    /** Look and feel information */
    private UIManager.LookAndFeelInfo[] LAFinfos;
    private String[] LAFnames; // Look and feel names
    
    private Settings settings;
    
    /** 
     * Creates new form PreferencesDialog.
     * 
     * @param parent The parent frame.
     * @param modal True if the dialog should be modal.
     */
    public PreferencesDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        settings = Settings.getInstance();
        
        // Get chosen look and feel
        
        String currentLAFclass = settings.getLookAndFeelClassName();
        int lafBoxIndex = 0;
        
        // Get all look and feels
        LAFinfos = UIManager.getInstalledLookAndFeels();                        
        
        LAFnames = new String[LAFinfos.length];
        for (int i = 0; i < LAFinfos.length; i++) {
            LAFnames[i] = LAFinfos[i].getName();
            if (LAFinfos[i].getClassName().equals(currentLAFclass)) {
                lafBoxIndex = i;
            }
        }
        
        LAFComboBox.setModel(new DefaultComboBoxModel(LAFnames));
        LAFComboBox.setSelectedIndex(lafBoxIndex);
        
        pack();
        setLocationRelativeTo(parent);        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        southPanel = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        centerPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        LAFLabel = new javax.swing.JLabel();
        LAFComboBox = new javax.swing.JComboBox();

        setTitle("Look and feel");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        buttonPanel.setLayout(new java.awt.GridLayout(1, 0, 5, 5));

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(okButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        buttonPanel.add(cancelButton);

        southPanel.add(buttonPanel);

        getContentPane().add(southPanel, java.awt.BorderLayout.SOUTH);

        centerPanel.setLayout(new java.awt.BorderLayout());

        LAFLabel.setText("Look and feel:");
        jPanel1.add(LAFLabel);

        LAFComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAFComboBoxActionPerformed(evt);
            }
        });

        jPanel1.add(LAFComboBox);

        centerPanel.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        
        // do nothing
        
        disposeDialog(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        
        // First: commit changes
        
        disposeDialog(true);
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * Disposes the dialog.
     *
     * @param saveChanges True if the changes should be saved.
     */
    private void disposeDialog(boolean saveChanges) {
        setVisible(false);        
        
        if (saveChanges) {            
            // dnd selection
            
            // ...
            
            // Look and feel
            UIManager.LookAndFeelInfo selectedLAFinfo = LAFinfos[LAFComboBox.getSelectedIndex()];
            String newLAFClassName = selectedLAFinfo.getClassName();                        
            settings.setLookAndFeelClassName(newLAFClassName); // store in settings; 
            
            String currentLAFClassName = UIManager.getLookAndFeel().getClass().getName();
            if (! (currentLAFClassName.equals(newLAFClassName))) {
                JOptionPane.showMessageDialog(this,"Note: Look and feel change will not take effect until next time you run the program.","Look and feel changed",JOptionPane.INFORMATION_MESSAGE);
            }            
            
            //ApplicationFrame.getInstance().setLookAndFeel(LAFClassName());
        }
        dispose();
    }
    
    private void LAFComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAFComboBoxActionPerformed
        // nothing                
    }//GEN-LAST:event_LAFComboBoxActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        disposeDialog(false); // Do not save
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new PreferencesDialog(new javax.swing.JFrame(), true).show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox LAFComboBox;
    private javax.swing.JLabel LAFLabel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel southPanel;
    // End of variables declaration//GEN-END:variables
    
}
